# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2019-2022 VMware, Inc. All rights reserved.
# Copyright (c) 2016-2019 Carbon Black, Inc. All rights reserved.

source-version: ${SHARED_COMPONENT_VERSION}
builder: centos7
builders:
    - gcc112-relwithdebinfo
    - gcc73-relwithdebinfo
    - gcc-arm-8_2-relwithdebinfo
service-env:
    PROJECT_VERSION:     ${SOURCE_VERSION}
    UTIL_DIR:            /src/util
    JOBS:                1
    PACKAGE_VERSION:     ${SOURCE_VERSION}

    KERNEL_API_VERSION: CB_EVENT_API_2_1

    # Override the kernel versions
    #  This should be a comma seperated list of kernel versions to match.  (This
    #  is a simple match in the string.)
    #  I.e.  "2.6.32-754,3.10.0-957" would build 6.9 and 7.6
    #        "754,957" would build 6.9 and 7.6
    #        "3.10.0" would build all 7.x versions
    #  NOTE: It is ok to inclued kernels from only one platform.
    KERNEL_OVERRIDE_LIST: ""
    BUILD_VERSION:
